# Generated by Django 5.0.2 on 2024-02-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
